# Generated by Django 6.1 on 2026-09-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_status_alter_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.customer'),
        ),
    ]
