# Generated by Django 6.1 on 2026-09-03 09:53

from decimal import Decimal
from django.db import migrations, models


def create_initial_profile(apps, schema_editor):
    BusinessSettings = apps.get_model('billing', 'BusinessSettings')
    BusinessProfile = apps.get_model('billing', 'BusinessProfile')
    Invoice = apps.get_model('billing', 'Invoice')
    Purchase = apps.get_model('billing', 'Purchase')
    settings = BusinessSettings.objects.order_by('pk').first()
    if settings:
        profile = BusinessProfile.objects.create(
            business_name=settings.business_name, address=settings.address,
            state=settings.state, gstin=settings.gstin, currency=settings.currency,
            default_gst_rate=settings.default_gst_rate, is_active=True,
            invoice_counter=settings.invoice_counter, purchase_counter=settings.purchase_counter,
        )
        values = {
            'profile_name': profile.business_name, 'profile_address': profile.address,
            'profile_gstin': profile.gstin, 'profile_state': profile.state,
            'profile_currency': profile.currency,
        }
        Invoice.objects.filter(profile_name='').update(**values)
        Purchase.objects.filter(profile_name='').update(**values)


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_receipt_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Shop', max_length=120)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15, verbose_name='GSTIN')),
                ('state', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(default='₹', max_length=5)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('logo', models.FileField(blank=True, upload_to='business_logos/')),
                ('is_active', models.BooleanField(default=False)),
                ('invoice_counter', models.PositiveIntegerField(default=1)),
                ('purchase_counter', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'business_name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_currency',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile_state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_currency',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_logo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_owner_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='profile_state',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.RunPython(create_initial_profile, migrations.RunPython.noop),
    ]
