# Generated by Django 6.1 on 2026-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_businessprofile_invoice_profile_address_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businessprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_business_profile'),
        ),
    ]
